#!/bin/bash

cat <<EOF | tee /root/.ssh/id_rsa
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAQEAuXMdx15NnIswvGM3AxUTqlhcD9GPs9AZ1e4p2GW3Y2D7vcJwE4r+
GaD7K8g6ABCy/2xyPIL31BPRMliyJiWcHbLyIPFu6Xqrlf6r98TZQRQ1z0XaOa4gYhF9VP
r65dQJSyHETf1+OsydAXcPRhRXk9Lwkakn7zQOuCMASo5KufgfbRSng+PhOyHG0b4oX01I
LCJJg8saRo205QPoAIMWS/pkS7q0XYq+muXIXQzqyb6MptmUyqnvgotIGpjK2M4Ry6Z/u3
dtNDT2/6+uyzz88DL5S1EBSFyNjcEFl/D5l+3v0jgmM+H37THIrKfHyYL5J2vbv7hbFoX0
b9EPjb5qDQAAA8DI1JIQyNSSEAAAAAdzc2gtcnNhAAABAQC5cx3HXk2cizC8YzcDFROqWF
wP0Y+z0BnV7inYZbdjYPu9wnATiv4ZoPsryDoAELL/bHI8gvfUE9EyWLImJZwdsvIg8W7p
equV/qv3xNlBFDXPRdo5riBiEX1U+vrl1AlLIcRN/X46zJ0Bdw9GFFeT0vCRqSfvNA64Iw
BKjkq5+B9tFKeD4+E7IcbRvihfTUgsIkmDyxpGjbTlA+gAgxZL+mRLurRdir6a5chdDOrJ
voym2ZTKqe+Ci0gamMrYzhHLpn+7d200NPb/r67LPPzwMvlLUQFIXI2NwQWX8PmX7e/SOC
Yz4fftMcisp8fJgvkna9u/uFsWhfRv0Q+NvmoNAAAAAwEAAQAAAQAiyoTwrTF0R+ypuxdL
/b1FvPPwh8kk28qtBtRU46hG/Z/c1sh98hp/pmLYsOSotHlQUAESdyOVZu5dOqSZYX7rV3
HzWjgLl1bveeq7PfPgMLFzpFAveApdO5i+w6MkUOY5cSlJ1F/FGjPuXW7BH/naIr29JfX2
+1Yzl2Vrl0xPnPpHbNaR8jtKbqKDMvMJsvn8QyLcn8VmwcOqdD3dK6o3bDBn5woowaZWLS
1L3w2ddxrFiDqw8yZasbvhSKuSnOaFSaTY4QYnh1XrroY8qB6KnEasRLq7pbvcg/alyyAa
PrEZl+5OOGvEOA1GHGGiR2HoG9glEtLSYbin7xGPPUgFAAAAgQC+FuD0Hu9cB5XOoJtv4I
SgR9x+UGtNYI1/VMTtNjgkSbjIIqkJ2oRWK/SODW0ZAmgkqbNlz7THeLKE3Kuzd1Zz4/UV
vFXwBaGLqAVi3VUUofheUq/zJpVs5kKw/ZxHXLEGA3JHEvij4fzqKp9K2ekKG5Bl4eBhK0
3ugcK1ku9qZQAAAIEA3+cDyQ8g1bvd2bH+/kN/skKbcRc307ecu67sDP7LMMd5k9A0FUbs
HEgc6OgSDZkSClgaY94TUWXVhF0/BWvCLxhR4Oi21sVc7bcSt7vHc6Z/OW3v3apJaC42Kb
POs4aZ+gpPQTDb0TRQi+5fc0yvd7n5Yp9hheJvKB4izILjuc8AAACBANQI7SkFtExiQzgw
WkeOt2rT3rBJCmphkV+QqyPU5kdbGgW4m1Zno9ZmyIz7arpIVThwyjjKfHBO409eOgrRar
l9q5FslYHe5RT8Jb42yJF0nnbKdxW+Fqd7PRZc5zSR56O9BPwe2OK6DLPGuPAX8iFOLbHN
2F2Jx2eyMafqgEFjAAAAB3NhbmpheWEBAgM=
-----END OPENSSH PRIVATE KEY-----
EOF

chmod 400 /root/.ssh/id_rsa

apt update
apt install git make
cd /usr/local/src/
git clone git@bitbucket.org:moresand/mos-cmb-bandc-worker.git
cd /usr/local/src/mos-cmb-bandc-worker
git pull origin Development
mv mos_cmb_bandc_jcb_worker/Makefile .
mv mos_cmb_bandc_jcb_worker/Dockerfile .
sed -i 's/"Url": "redis.moresanddc.uk"/"Url": "sandbox-redis.moresanddc.uk"/g' mos_cmb_bandc_jcb_worker/appsettings.json
sed -i 's/"AccessKeyId": "AKIA2NFBWRNX7SGXBLS7"/"AccessKeyId": "AKIA2NFBWRNX3YL2KT6P"/g' mos_cmb_bandc_jcb_worker/appsettings.json
sed -i 's/"SecretAccessKey": "bx5zKL7nTpqts2ooWHUusO\/zRqesoez+4FYytDSS"/"SecretAccessKey": "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"/g' mos_cmb_bandc_jcb_worker/appsettings.json
make ENV=PROD rebuild

cat <<EOF | tee /root/.ssh/id_rsa
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAQEAuXMdx15NnIswvGM3AxUTqlhcD9GPs9AZ1e4p2GW3Y2D7vcJwE4r+
GaD7K8g6ABCy/2xyPIL31BPRMliyJiWcHbLyIPFu6Xqrlf6r98TZQRQ1z0XaOa4gYhF9VP
r65dQJSyHETf1+OsydAXcPRhRXk9Lwkakn7zQOuCMASo5KufgfbRSng+PhOyHG0b4oX01I
LCJJg8saRo205QPoAIMWS/pkS7q0XYq+muXIXQzqyb6MptmUyqnvgotIGpjK2M4Ry6Z/u3
dtNDT2/6+uyzz88DL5S1EBSFyNjcEFl/D5l+3v0jgmM+H37THIrKfHyYL5J2vbv7hbFoX0
b9EPjb5qDQAAA8DI1JIQyNSSEAAAAAdzc2gtcnNhAAABAQC5cx3HXk2cizC8YzcDFROqWF
wP0Y+z0BnV7inYZbdjYPu9wnATiv4ZoPsryDoAELL/bHI8gvfUE9EyWLImJZwdsvIg8W7p
equV/qv3xNlBFDXPRdo5riBiEX1U+vrl1AlLIcRN/X46zJ0Bdw9GFFeT0vCRqSfvNA64Iw
BKjkq5+B9tFKeD4+E7IcbRvihfTUgsIkmDyxpGjbTlA+gAgxZL+mRLurRdir6a5chdDOrJ
voym2ZTKqe+Ci0gamMrYzhHLpn+7d200NPb/r67LPPzwMvlLUQFIXI2NwQWX8PmX7e/SOC
Yz4fftMcisp8fJgvkna9u/uFsWhfRv0Q+NvmoNAAAAAwEAAQAAAQAiyoTwrTF0R+ypuxdL
/b1FvPPwh8kk28qtBtRU46hG/Z/c1sh98hp/pmLYsOSotHlQUAESdyOVZu5dOqSZYX7rV3
HzWjgLl1bveeq7PfPgMLFzpFAveApdO5i+w6MkUOY5cSlJ1F/FGjPuXW7BH/naIr29JfX2
+1Yzl2Vrl0xPnPpHbNaR8jtKbqKDMvMJsvn8QyLcn8VmwcOqdD3dK6o3bDBn5woowaZWLS
1L3w2ddxrFiDqw8yZasbvhSKuSnOaFSaTY4QYnh1XrroY8qB6KnEasRLq7pbvcg/alyyAa
PrEZl+5OOGvEOA1GHGGiR2HoG9glEtLSYbin7xGPPUgFAAAAgQC+FuD0Hu9cB5XOoJtv4I
SgR9x+UGtNYI1/VMTtNjgkSbjIIqkJ2oRWK/SODW0ZAmgkqbNlz7THeLKE3Kuzd1Zz4/UV
vFXwBaGLqAVi3VUUofheUq/zJpVs5kKw/ZxHXLEGA3JHEvij4fzqKp9K2ekKG5Bl4eBhK0
3ugcK1ku9qZQAAAIEA3+cDyQ8g1bvd2bH+/kN/skKbcRc307ecu67sDP7LMMd5k9A0FUbs
HEgc6OgSDZkSClgaY94TUWXVhF0/BWvCLxhR4Oi21sVc7bcSt7vHc6Z/OW3v3apJaC42Kb
POs4aZ+gpPQTDb0TRQi+5fc0yvd7n5Yp9hheJvKB4izILjuc8AAACBANQI7SkFtExiQzgw
WkeOt2rT3rBJCmphkV+QqyPU5kdbGgW4m1Zno9ZmyIz7arpIVThwyjjKfHBO409eOgrRar
l9q5FslYHe5RT8Jb42yJF0nnbKdxW+Fqd7PRZc5zSR56O9BPwe2OK6DLPGuPAX8iFOLbHN
2F2Jx2eyMafqgEFjAAAAB3NhbmpheWEBAgM=
-----END OPENSSH PRIVATE KEY-----
EOF

