---
- hosts: localhost
  connection: local
  tasks:

   - name: launching aws
     amazon.aws.ec2_instance:
       name: "public-compute-instance"
       image_id: "ami-050949f5d3aede071"
       key_name: "sanjaya"
       region: eu-west-2
       count: 1
       instance_type: t2.micro
       wait: yes
       user_data: "{{ lookup('file', '{{ script }}') }}"
     register: ec2

   
    
   - name: save result
     local_action:  copy content={{ ec2 }} dest=/"$PWD"/instance_details

   - name: instance_replace
     shell: sh /"$PWD"/instance_replace.sh

   
